name: oca
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  ffigen: ^8.0.0
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.77.1
